#!/usr/bin/env python3
"""
Add-on metrics — NO change to strategy logic, no new strategy computation.
Reads: the committed backtest (rerun unchanged via backtest_path2.py) and the
Stooq market series in data/prices/ (ES continuous futures close; SPY and AGG
adjusted ETF closes).
Writes: two sections appended to strategy_results.md — (1) time in market and
capital utilization, (2) beta/correlation to equities and bonds.
"""
import re
import runpy
from pathlib import Path

import numpy as np
import pandas as pd

REPO = Path(__file__).resolve().parent.parent
RESULTS = REPO / "strategy_results.md"
MARK_A = "## Add-on exhibit: time in market and capital utilization"
MARK_B = "## Add-on exhibit: beta to equities and bonds"

# the backtest rewrites strategy_results.md from scratch; snapshot and restore
# so earlier appended sections survive, then append these two idempotently
snapshot = RESULTS.read_text()
bt = runpy.run_path(REPO / "scripts/backtest_path2.py")
RESULTS.write_text(snapshot)

CAPITAL = bt["CAPITAL"]
ORDER = bt["ORDER"]
POINT_SIZE = bt["POINT_SIZE"]
VARIANTS = bt["VARIANTS"]
frames = bt["frames"]
all_days = bt["all_days"]
SUBPERIODS = bt["SUBPERIODS"]

# ---------------- A1. time in market / exposure / margin usage (overlay)
per_mkt = {}
gross_expo = pd.Series(0.0, index=all_days)
margin_used = pd.Series(0.0, index=all_days)
margin_known = pd.Series(0.0, index=all_days)   # notional-weighted coverage flag
any_pos = pd.Series(False, index=all_days)
for p in ORDER:
    r = VARIANTS["overlay"][p]
    held = r.pos_enter.abs()
    per_mkt[p] = dict(tim=(held > 0).mean())
    notional = (held * frames[p].U.reindex(r.index) * POINT_SIZE[p]).reindex(all_days).fillna(0.0)
    gross_expo = gross_expo + notional
    ml = frames[p].mlevel.reindex(r.index)
    margin_used = margin_used + (held * ml).reindex(all_days).fillna(0.0)
    margin_known = margin_known + (held * ml.notna()).reindex(all_days).fillna(0.0)
    any_pos = any_pos | (held.reindex(all_days).fillna(0.0) > 0)

tim_port = any_pos.mean()
avg_gross = (gross_expo / CAPITAL).mean()
avg_margin = (margin_used / CAPITAL).mean()
clean = [d for d in all_days if d >= "2009-01-12"]        # all 9 have margin data
avg_margin_clean = (margin_used[clean] / CAPITAL).mean()
avg_gross_clean = (gross_expo[clean] / CAPITAL).mean()

# ---------------- A2. beta / correlation to equities and bonds
def load_close(name):
    s = pd.read_csv(REPO / f"data/prices/{name}")
    return s.set_index("date").close.sort_index()


port_net = bt["PORT"]["overlay"].net / CAPITAL
base_net = bt["PORT"]["baseline"].net / CAPITAL

# plain OLS of y on x: beta, classical-SE 95% CI, R-squared, correlation
def ols(y, x):
    y = np.asarray(y, dtype=float)
    x = np.asarray(x, dtype=float)
    n = len(y)
    xd, yd = x - x.mean(), y - y.mean()
    beta = (xd * yd).sum() / (xd ** 2).sum()
    alpha = y.mean() - beta * x.mean()
    resid = y - alpha - beta * x
    se = np.sqrt((resid ** 2).sum() / (n - 2) / (xd ** 2).sum())
    r2 = 1 - (resid ** 2).sum() / (yd ** 2).sum()
    corr = np.corrcoef(x, y)[0, 1]
    return dict(n=n, beta=beta, se=se, lo=beta - 1.96 * se, hi=beta + 1.96 * se,
                r2=r2, corr=corr)


es = load_close("stooq_ES_continuous_close.csv").pct_change().dropna()
spy = load_close("stooq_SPY_adjusted_close.csv").pct_change().dropna()
agg = load_close("stooq_AGG_adjusted_close.csv").pct_change().dropna()

# match strategy-return days to market-return days (intersection of calendars)
def aligned(ret, mkt):
    idx = ret.index.intersection(mkt.index)
    return ret[idx], mkt[idx]


# regressions: full sample + four sub-periods vs ES; SPY/AGG comparisons
rows = []
y, x = aligned(port_net, es)
full = ols(y, x)
rows.append(("Full 2001–2024.03", full))
for name, a, b in SUBPERIODS:
    seg = port_net[(port_net.index >= a) & (port_net.index <= b)]
    ys, xs = aligned(seg, es)
    rows.append((name, ols(ys, xs)))
yb, xb = aligned(base_net, es)
base_full = ols(yb, xb)
ysp, xsp = aligned(port_net, spy)
spy_full = ols(ysp, xsp)
yag, xag = aligned(port_net, agg)
agg_full = ols(yag, xag)
agg_sub = []
for name, a, b in SUBPERIODS:
    seg = port_net[(port_net.index >= a) & (port_net.index <= b)]
    ys, xs = aligned(seg, agg)
    agg_sub.append((name, ols(ys, xs) if len(ys) > 100 else None))
# sanity: the two equity series must agree with each other on overlap
e_o, s_o = aligned(es, spy)
xcheck = np.corrcoef(np.asarray(e_o, float), np.asarray(s_o, float))[0, 1]

# ---------------- write sections
sec_a = f"""{MARK_A}

Generated by scripts/exposure_beta_exhibit.py from the committed backtest rerun
unchanged (overlay variant, fractional contracts). Notional = unadjusted Stooq
front price × point size (the spec §1 convention); margin = maintenance level
in effect that day.

| Measure | Full sample | 2009-01-12+ (all 9 margined) |
|---|---|---|
| Trading days with any position (portfolio) | {tim_port*100:.1f}% | — |
| Average gross exposure / capital | {avg_gross*100:.0f}% | {avg_gross_clean*100:.0f}% |
| Average maintenance margin posted / capital | {avg_margin*100:.2f}% | {avg_margin_clean*100:.2f}% |

Per-market share of days with a position: """ + ", ".join(
    f"{p} {per_mkt[p]['tim']*100:.1f}%" for p in ORDER) + f"""

**Idle capital, stated plainly:** the portfolio holds positions on
{tim_port*100:.1f}% of days and runs ≈{avg_gross*100:.0f}% of capital in gross
futures notional, but the cash actually consumed as maintenance margin averages
only {avg_margin*100:.1f}% of the $500K ({avg_margin_clean*100:.1f}% once all
nine markets have margin data; CME speculative initial margin ≈ 110% of
maintenance, so ≈{avg_margin_clean*1.1*100:.1f}% at initiation). Roughly
{100-avg_margin_clean*1.1*100:.0f}% of capital sits in cash at all times — an
opportunity cost if left unremunerated, or T-bill yield if swept, which this
backtest does not credit (returns are excess-return-style, rf = 0, per R8).
Pre-2009 the margin-usage figure is understated because metals/CL margin
history has not started (disclosed, not backfilled).

"""

def fmt_ols(m):
    return (f"{m['beta']:+.4f} | [{m['lo']:+.4f}, {m['hi']:+.4f}] | "
            f"{m['r2']*100:.2f}% | {m['corr']:+.3f} | {m['n']:,}")


sec_b = f"""{MARK_B}

Equity series: **Stooq es.f** — E-mini S&P 500 continuous futures front-month
splice (same free source family as the committed futures data; unadjusted
splice, ~4 small quarterly roll jumps/yr add noise but no directional bias).
Chosen because Stooq's free ETF depth stops at 2005-02 and its cash-index
series (^SPX, renamed ^USLC) only reaches back to 2013. Cross-checks: ES vs
SPY daily-return correlation on 2005+ overlap = {xcheck:.3f}; overlay-vs-SPY
full-overlap beta = {spy_full['beta']:+.4f} (vs ES-based
{ols(*aligned(port_net[port_net.index >= '2005-02-25'], es))['beta']:+.4f} on
the same window). Bond series: **Stooq agg.us** — iShares Core U.S. Aggregate
Bond ETF, adjusted close, 2005-02-25 → 2024-03-28 (83% of sample). OLS of
daily overlay net returns on market daily returns; 95% CI = ±1.96 classical SE.

| Window | Beta vs ES | 95% CI | R² | Corr | Days |
|---|---|---|---|---|---|
""" + "\n".join(f"| {name} | {fmt_ols(m)} |" for name, m in rows) + f"""
| Full, baseline variant | {fmt_ols(base_full)} |

Bond correlation (overlay net vs AGG): full overlap corr = {agg_full['corr']:+.3f}
(beta {agg_full['beta']:+.4f}, R² {agg_full['r2']*100:.2f}%); by sub-period: """ + ", ".join(
    f"{name} {m['corr']:+.3f}" for name, m in agg_sub if m) + f"""

**Stated plainly:** the strategy is effectively equity-market-neutral — a PM
would book it as such — with a small but statistically significant NEGATIVE
equity beta ({full['beta']:+.3f}, CI excludes zero, stable in sign across all
four sub-periods): equity direction explains under
{max(m['r2'] for _, m in rows)*100:.1f}% of daily variance in every window, and
what dependence exists makes it a mild diversifier, not a hidden long. Bond
neutrality holds on the full sample (corr {agg_full['corr']:+.2f}) but NOT
period-by-period: in 2021–2024.03 the correlation to AGG was
{agg_sub[-1][1]['corr']:+.2f}, because the trend overlay was short fixed income
through the 2022 hiking cycle — a real, if episodic, bond-direction exposure.
"""

# drop only this script's old sections (if present), then re-append at the end
text = RESULTS.read_text()
for mark in (MARK_A, MARK_B):
    text = re.sub(re.escape(mark) + r".*?(?=\n## |\Z)", "", text, flags=re.S)
RESULTS.write_text(text.rstrip() + "\n\n" + sec_a + sec_b)
print(f"time-in-market {tim_port*100:.1f}% | gross expo {avg_gross*100:.0f}% | "
      f"margin used {avg_margin*100:.2f}% (clean {avg_margin_clean*100:.2f}%)")
print(f"beta vs ES {full['beta']:+.4f} CI [{full['lo']:+.4f},{full['hi']:+.4f}] "
      f"R2 {full['r2']*100:.2f}% corr {full['corr']:+.3f} | AGG corr {agg_full['corr']:+.3f}")
print("appended 2 sections to strategy_results.md")
