#!/usr/bin/env python3
"""
Add-on exhibit — NO change to strategy logic. Stationary block bootstrap
(Politis-Romano, mean 21-td blocks, seed 42) of the overlay's net daily
returns: 1,000 resampled equity curves vs the actual one.
Reads: the committed backtest (rerun unchanged via backtest_path2.py).
Writes: monte_carlo_exhibit.png + one section appended to strategy_results.md.
"""
import re
import runpy
from pathlib import Path

import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

REPO = Path(__file__).resolve().parent.parent
RESULTS = REPO / "strategy_results.md"
SECTION_MARK = "## Add-on exhibit: block-bootstrap Monte Carlo"

# the backtest rewrites strategy_results.md from scratch; snapshot and restore
# so sections appended by other exhibit scripts survive a rerun of this one
snapshot = RESULTS.read_text()
bt = runpy.run_path(REPO / "scripts/backtest_path2.py")
RESULTS.write_text(snapshot)
net = bt["PORT"]["overlay"].net            # daily net $ P&L, overlay variant
CAPITAL = bt["CAPITAL"]
r = (net / CAPITAL).to_numpy()             # daily net return on capital
dates = bt["pd"].to_datetime(net.index)
n = len(r)

rng = np.random.default_rng(42)
N_PATHS = 1000
MEAN_BLOCK = 21


def stationary_bootstrap_indices():
    idx, total = [], 0
    while total < n:
        start = int(rng.integers(0, n))
        length = int(rng.geometric(1.0 / MEAN_BLOCK))
        take = min(length, n - total)
        idx.append(np.arange(start, start + take) % n)
        total += take
    return np.concatenate(idx)


# simulate 1,000 resampled cumulative curves; percentile of the actual terminal
paths = np.empty((N_PATHS, n))
for k in range(N_PATHS):
    paths[k] = np.cumsum(r[stationary_bootstrap_indices()])

actual = np.cumsum(r)
term = paths[:, -1]
pct = (np.sum(term < actual[-1]) + 0.5 * np.sum(term == actual[-1])) / N_PATHS * 100
q05, q50, q95 = np.percentile(term, [5, 50, 95])

# ---- chart: gray spaghetti + actual curve in the overlay's blue
BLUE, GRAY = "#2a78d6", "#c9c9c9"
plt.rcParams.update({"font.size": 10, "axes.edgecolor": "#cccccc",
                     "axes.labelcolor": "#333333", "text.color": "#333333",
                     "xtick.color": "#555555", "ytick.color": "#555555",
                     "axes.grid": True, "grid.color": "#e8e8e8",
                     "grid.linewidth": 0.7, "figure.facecolor": "white",
                     "axes.facecolor": "white"})
fig, ax = plt.subplots(figsize=(10, 5.5))
for k in range(N_PATHS):
    ax.plot(dates, paths[k] * 100, color=GRAY, lw=0.4, alpha=0.12, zorder=1)
ax.plot(dates, actual * 100, color=BLUE, lw=2.0, zorder=3, label="actual overlay net")
ax.annotate("actual overlay net", (dates[-1], actual[-1] * 100), xytext=(6, 0),
            textcoords="offset points", color=BLUE, fontsize=9, va="center")
ax.annotate(f"actual terminal: {actual[-1]*100:.1f}% of capital\n"
            f"= {pct:.0f}th percentile of {N_PATHS:,} bootstrap paths\n"
            f"(sim 5th/50th/95th: {q05*100:.0f}% / {q50*100:.0f}% / {q95*100:.0f}%)",
            xy=(0.02, 0.97), xycoords="axes fraction", va="top", fontsize=9,
            color="#333333")
ax.set_title("Overlay net equity vs 1,000 stationary-block-bootstrap resamples "
             "(21-day mean blocks, seed 42)")
ax.set_ylabel("cumulative net P&L, % of $500K capital")
ax.margins(x=0.10)
for s in ["top", "right"]:
    ax.spines[s].set_visible(False)
fig.tight_layout()
fig.savefig(REPO / "monte_carlo_exhibit.png", dpi=150)
plt.close(fig)

section = f"""{SECTION_MARK}

Generated by scripts/monte_carlo_exhibit.py after the main report (rerunning it
re-appends this section); no strategy logic touched. The overlay variant's net
daily returns were resampled into {N_PATHS:,} alternative equity curves with a
stationary block bootstrap (geometric block lengths, mean {MEAN_BLOCK} trading
days, wrap-around, seed 42). Because every path is drawn from the same realized
return distribution, this is a path-luck exhibit — how much of the terminal
outcome is sequencing — not an independent test of the strategy.

- Actual terminal net P&L: {actual[-1]*100:.1f}% of capital — the
  **{pct:.0f}th percentile** of the simulated terminal distribution.
- Simulated terminal P&L percentiles: 5th {q05*100:.1f}%, median {q50*100:.1f}%,
  95th {q95*100:.1f}% of capital.

![Monte Carlo](monte_carlo_exhibit.png)
"""

# drop only this script's old section (if present), then re-append at the end
text = re.sub(re.escape(SECTION_MARK) + r".*?(?=\n## |\Z)", "",
              RESULTS.read_text(), flags=re.S)
RESULTS.write_text(text.rstrip() + "\n\n" + section)
print(f"\nactual terminal {actual[-1]*100:.2f}% of capital = {pct:.1f}th percentile "
      f"of {N_PATHS} paths (sim 5/50/95: {q05*100:.1f}/{q50*100:.1f}/{q95*100:.1f}%)")
print("wrote monte_carlo_exhibit.png and appended section to strategy_results.md")
