#!/usr/bin/env python3
"""
Packaging additions — NO change to strategy logic, no new strategy computation.
Reads: the committed backtest (rerun unchanged via backtest_path2.py) and the
Stooq SPY/ES series in data/prices/.
Writes: two sections appended to strategy_results.md — (1) beta and correlation
of the overlay's net daily returns vs the S&P 500, (2) leave-one-market-out
Sharpe table (overlay net, portfolio P&L minus one market's P&L at a time —
exact, since sizing is per-market independent and portfolio net is the sum).
"""
import re
import runpy
from pathlib import Path

import numpy as np
import pandas as pd

REPO = Path(__file__).resolve().parent.parent
RESULTS = REPO / "strategy_results.md"
MARK_BETA = "## Beta and correlation"
MARK_LOMO = "## Leave-one-market-out (overlay net)"

# the backtest rewrites strategy_results.md from scratch; snapshot and restore
# so earlier appended sections survive, then append these two idempotently
snapshot = RESULTS.read_text()
bt = runpy.run_path(REPO / "scripts/backtest_path2.py")
RESULTS.write_text(snapshot)

CAPITAL = bt["CAPITAL"]
ORDER = bt["ORDER"]
VARIANTS = bt["VARIANTS"]
PORT = bt["PORT"]
all_days = bt["all_days"]
metrics = bt["metrics"]

port_net = PORT["overlay"].net / CAPITAL


def load_close(name):
    s = pd.read_csv(REPO / f"data/prices/{name}")
    return s.set_index("date").close.sort_index()


# plain OLS of y on x: beta, classical SE, R-squared, correlation
def ols(y, x):
    y = np.asarray(y, dtype=float)
    x = np.asarray(x, dtype=float)
    n = len(y)
    xd, yd = x - x.mean(), y - y.mean()
    beta = (xd * yd).sum() / (xd ** 2).sum()
    alpha = y.mean() - beta * x.mean()
    resid = y - alpha - beta * x
    se = np.sqrt((resid ** 2).sum() / (n - 2) / (xd ** 2).sum())
    r2 = 1 - (resid ** 2).sum() / (yd ** 2).sum()
    corr = np.corrcoef(x, y)[0, 1]
    return dict(n=n, beta=beta, se=se, r2=r2, corr=corr)


def aligned(ret, mkt):
    idx = ret.index.intersection(mkt.index)
    return ret[idx], mkt[idx]


spy = load_close("stooq_SPY_adjusted_close.csv").pct_change().dropna()
es = load_close("stooq_ES_continuous_close.csv").pct_change().dropna()
m_spy = ols(*aligned(port_net, spy))
m_es = ols(*aligned(port_net, es))

sec_beta = f"""{MARK_BETA}

OLS of overlay net daily returns on S&P 500 daily returns (generated by
scripts/packaging_beta_lomo.py from the committed backtest rerun unchanged).
SPY is the Stooq adjusted ETF close, which starts 2005-02-25; the ES continuous
futures row covers the full sample and is the same regression already reported
in the equity/bond beta exhibit above.

| Market series | Window | Beta | SE(beta) | Corr | R² | Days |
|---|---|---|---|---|---|---|
| SPY (Stooq adj.) | 2005-02-28 → 2024-03-28 | {m_spy['beta']:+.4f} | {m_spy['se']:.4f} | {m_spy['corr']:+.3f} | {m_spy['r2']*100:.2f}% | {m_spy['n']:,} |
| ES cont. futures | full 2001 → 2024-03-28 | {m_es['beta']:+.4f} | {m_es['se']:.4f} | {m_es['corr']:+.3f} | {m_es['r2']*100:.2f}% | {m_es['n']:,} |

Beta to the S&P 500 is {m_spy['beta']:+.3f} (SE {m_spy['se']:.4f} — about
{abs(m_spy['beta']/m_spy['se']):.0f} SEs below zero), correlation
{m_spy['corr']:+.2f}: economically negligible and slightly negative.
"""

# ---------------- leave-one-market-out: portfolio net minus one market's net.
# Exact, not approximate: sizing/costs are computed per market independently
# and portfolio net is their sum, so dropping a market IS the 8-market portfolio.
full_m = metrics(PORT["overlay"].net)
lomo_rows = []
for p in ORDER:
    net_wo = PORT["overlay"].net - VARIANTS["overlay"][p].net.reindex(all_days).fillna(0.0)
    m = metrics(net_wo)
    lomo_rows.append((p, m))

sh = [m["sharpe"] for _, m in lomo_rows]
sec_lomo = f"""{MARK_LOMO}

Overlay net Sharpe recomputed nine times, each time excluding one market
(portfolio P&L minus that market's P&L — exact, since sizing is per-market
independent). Full 9-market overlay net Sharpe: {full_m['sharpe']:.2f}.

| Excluded market | Sharpe | Δ vs full | Ann ret | Ann vol | Max DD |
|---|---|---|---|---|---|
""" + "\n".join(
    f"| {p} | {m['sharpe']:.2f} | {m['sharpe']-full_m['sharpe']:+.2f} | "
    f"{m['ann_ret']*100:.2f}% | {m['ann_vol']*100:.2f}% | {m['max_dd']*100:.1f}% |"
    for p, m in lomo_rows) + f"""

Sharpe stays in [{min(sh):.2f}, {max(sh):.2f}] whichever market is dropped —
no single market carries the result.
"""

# drop only this script's old sections (if present), then re-append at the end
text = RESULTS.read_text()
for mark in (MARK_BETA, MARK_LOMO):
    text = re.sub(re.escape(mark) + r"\n.*?(?=\n## |\Z)", "", text, flags=re.S)
RESULTS.write_text(text.rstrip() + "\n\n" + sec_beta + "\n" + sec_lomo)

print(f"beta vs SPY {m_spy['beta']:+.4f} SE {m_spy['se']:.4f} corr {m_spy['corr']:+.3f} "
      f"n={m_spy['n']} | vs ES {m_es['beta']:+.4f} SE {m_es['se']:.4f} corr {m_es['corr']:+.3f}")
print("LOMO Sharpe: " + ", ".join(f"{p} {m['sharpe']:.2f}" for p, m in lomo_rows)
      + f" | full {full_m['sharpe']:.2f}")
print("appended 2 sections to strategy_results.md")
