#!/usr/bin/env python3
"""
Packaging additions — NO change to strategy logic, no new strategy computation.
Reads: the committed backtest (rerun unchanged via backtest_path2.py), the Yahoo
SPY / ^GSPC closes in data/prices/ (written by scripts/fetch_yahoo_sp500.py) and
the Stooq SPY / ES series already committed there.
Writes: two sections appended to strategy_results.md — (1) beta and correlation
of the overlay's net daily returns vs the S&P 500 over the full backtest sample,
(2) leave-one-market-out Sharpe table (overlay net, portfolio P&L minus one
market's P&L at a time — exact, since sizing is per-market independent and
portfolio net is the sum).
"""
import re
import runpy
from pathlib import Path

import numpy as np
import pandas as pd

REPO = Path(__file__).resolve().parent.parent
RESULTS = REPO / "strategy_results.md"
MARK_BETA = "## Beta and correlation"
MARK_LOMO = "## Leave-one-market-out (overlay net)"
W0, W1 = "2001-01-02", "2024-03-28"          # the backtest sample
NW_LAG = 21                                  # Newey-West lags (one trading month)

# the backtest rewrites strategy_results.md from scratch; snapshot and restore
# so earlier appended sections survive, then append these two idempotently
snapshot = RESULTS.read_text()
bt = runpy.run_path(REPO / "scripts/backtest_path2.py")
RESULTS.write_text(snapshot)

CAPITAL = bt["CAPITAL"]
ORDER = bt["ORDER"]
VARIANTS = bt["VARIANTS"]
PORT = bt["PORT"]
all_days = bt["all_days"]
metrics = bt["metrics"]

port_net = PORT["overlay"].net / CAPITAL


def load_close(name, col="close"):
    s = pd.read_csv(REPO / f"data/prices/{name}")
    return s.set_index("date")[col].sort_index()


# plain OLS of y on x: beta, classical SE, Newey-West (Bartlett) SE, R², corr
def ols(y, x, lag=NW_LAG):
    y = np.asarray(y, dtype=float)
    x = np.asarray(x, dtype=float)
    n = len(y)
    xd, yd = x - x.mean(), y - y.mean()
    sxx = (xd ** 2).sum()
    beta = (xd * yd).sum() / sxx
    alpha = y.mean() - beta * x.mean()
    resid = y - alpha - beta * x
    se = np.sqrt((resid ** 2).sum() / (n - 2) / sxx)
    u = xd * resid
    s_nw = (u * u).sum()
    for k in range(1, lag + 1):
        s_nw += 2 * (1 - k / (lag + 1)) * (u[k:] * u[:-k]).sum()
    se_nw = np.sqrt(s_nw) / sxx
    r2 = 1 - (resid ** 2).sum() / (yd ** 2).sum()
    corr = np.corrcoef(x, y)[0, 1]
    return dict(n=n, beta=beta, se=se, se_nw=se_nw, r2=r2, corr=corr)


# restrict the market series to the backtest sample, then match calendars
# (intersection: strategy days without a market print — US equity holidays on
# which CME traded — are dropped)
def aligned(ret, mkt):
    mkt = mkt[(mkt.index >= W0) & (mkt.index <= W1)]
    idx = ret.index.intersection(mkt.index)
    return ret[idx], mkt[idx], len(ret.index.difference(mkt.index))


spy_y = load_close("yahoo_SPY_daily_close.csv", "adj_close").pct_change().dropna()
gspc = load_close("yahoo_GSPC_daily_close.csv").pct_change().dropna()
spy_s = load_close("stooq_SPY_adjusted_close.csv").pct_change().dropna()
es = load_close("stooq_ES_continuous_close.csv").pct_change().dropna()

y1, x1, dropped = aligned(port_net, spy_y)
m_spy = ols(y1, x1)
m_gspc = ols(*aligned(port_net, gspc)[:2])
m_spy_s = ols(*aligned(port_net, spy_s)[:2])
m_es = ols(*aligned(port_net, es)[:2])
# vendor cross-check: Yahoo vs Stooq SPY on Stooq's 2005-02-28+ overlap
ov = spy_y.index.intersection(spy_s.index)
xcheck_corr = np.corrcoef(np.asarray(spy_y[ov], float), np.asarray(spy_s[ov], float))[0, 1]
m_spy_y_ov = ols(*aligned(port_net[port_net.index >= ov.min()], spy_y)[:2])
tstat_nw = m_spy["beta"] / m_spy["se_nw"]
w_lo, w_hi = y1.index.min(), y1.index.max()


def fmt(m):
    return (f"{m['beta']:+.4f} | {m['se']:.4f} | {m['se_nw']:.4f} | {m['corr']:+.3f} | "
            f"{m['r2']*100:.2f}% | {m['n']:,}")


sec_beta = f"""{MARK_BETA}

OLS of overlay net daily returns on S&P 500 daily returns over the full
backtest sample, {w_lo} → {w_hi} (generated by
scripts/packaging_beta_lomo.py from the committed backtest rerun unchanged).
Primary series: **SPY dividend-adjusted close from Yahoo Finance** (free,
keyless, fetched by scripts/fetch_yahoo_sp500.py); the S&P 500 cash index
(^GSPC, same source) is the robustness row. The Stooq SPY row is the earlier
2005-02-28+ figure (Stooq's free ETF depth starts there) and the ES continuous
futures row is the regression already reported in the equity/bond beta exhibit
above. SE = classical OLS; NW SE = Newey-West with {NW_LAG} lags. Strategy days
with no equity print ({dropped} US equity holidays on which CME traded) are
dropped; no equity days lack a strategy return. Vendor check: Yahoo vs Stooq
SPY daily-return correlation on the overlap = {xcheck_corr:.4f}, and the Yahoo
series gives beta {m_spy_y_ov['beta']:+.4f} on Stooq's window vs Stooq's
{m_spy_s['beta']:+.4f}.

| Market series | Window | Beta | SE | NW SE | Corr | R² | Days |
|---|---|---|---|---|---|---|---|
| SPY adj. (Yahoo) | {w_lo} → {w_hi} | {fmt(m_spy)} |
| ^GSPC (Yahoo) | {w_lo} → {w_hi} | {fmt(m_gspc)} |
| SPY adj. (Stooq) | 2005-02-28 → {w_hi} | {fmt(m_spy_s)} |
| ES cont. futures (Stooq) | {w_lo} → {w_hi} | {fmt(m_es)} |

Beta to the S&P 500 over the full sample is {m_spy['beta']:+.2f} (SE
{m_spy['se']:.4f}; Newey-West SE {m_spy['se_nw']:.4f}, about
{abs(tstat_nw):.0f} robust SEs below zero), correlation {m_spy['corr']:+.2f}:
economically negligible and slightly negative, and the same to three decimals
whether the index is measured by SPY, the cash index, or ES futures.
"""

# ---------------- leave-one-market-out: portfolio net minus one market's net.
# Exact, not approximate: sizing/costs are computed per market independently
# and portfolio net is their sum, so dropping a market IS the 8-market portfolio.
full_m = metrics(PORT["overlay"].net)
lomo_rows = []
for p in ORDER:
    net_wo = PORT["overlay"].net - VARIANTS["overlay"][p].net.reindex(all_days).fillna(0.0)
    m = metrics(net_wo)
    lomo_rows.append((p, m))

sh = [m["sharpe"] for _, m in lomo_rows]
sec_lomo = f"""{MARK_LOMO}

Overlay net Sharpe recomputed nine times, each time excluding one market
(portfolio P&L minus that market's P&L — exact, since sizing is per-market
independent). Full 9-market overlay net Sharpe: {full_m['sharpe']:.2f}.

| Excluded market | Sharpe | Δ vs full | Ann ret | Ann vol | Max DD |
|---|---|---|---|---|---|
""" + "\n".join(
    f"| {p} | {m['sharpe']:.2f} | {m['sharpe']-full_m['sharpe']:+.2f} | "
    f"{m['ann_ret']*100:.2f}% | {m['ann_vol']*100:.2f}% | {m['max_dd']*100:.1f}% |"
    for p, m in lomo_rows) + f"""

Sharpe stays in [{min(sh):.2f}, {max(sh):.2f}] whichever market is dropped —
no single market carries the result.
"""

# drop only this script's old sections (if present), then re-append at the end
text = RESULTS.read_text()
for mark in (MARK_BETA, MARK_LOMO):
    text = re.sub(re.escape(mark) + r"\n.*?(?=\n## |\Z)", "", text, flags=re.S)
RESULTS.write_text(text.rstrip() + "\n\n" + sec_beta + "\n" + sec_lomo)

print(f"beta vs SPY(Yahoo) {m_spy['beta']:+.4f} SE {m_spy['se']:.4f} NW {m_spy['se_nw']:.4f} "
      f"corr {m_spy['corr']:+.3f} n={m_spy['n']} | ^GSPC {m_gspc['beta']:+.4f} | "
      f"SPY(Stooq) {m_spy_s['beta']:+.4f} | ES {m_es['beta']:+.4f}")
print("LOMO Sharpe: " + ", ".join(f"{p} {m['sharpe']:.2f}" for p, m in lomo_rows)
      + f" | full {full_m['sharpe']:.2f}")
print("appended 2 sections to strategy_results.md")
